export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_CARTLIST = "ADD_CARTLIST";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const ADD_COMPARELIST = "ADD_COMPARELIST";
export const GET_CARTLIST = "GET_CARTLIST";
export const GET_WISHLIST = "GET_WISHLIST";
export const GET_COMPARELIST = "GET_COMPARELIST";
export const DELTE_CARTLIST = "DELTE_CARTLIST";
